insert into exercises (id,name,exercise_level) values 1,"Wyciskanie na ławce skośnej w górę sztangą","ADVANCED";
insert into exercises (id,name,exercise_level) values 2,"Pompki w podporze tyłem na ławeczce","BEGINNER";
insert into exercises (id,name,exercise_level) values 3,"Rotacje z gumą","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 4,"Rowerek","BEGINNER";
insert into exercises (id,name,exercise_level) values 5,"Izometryczny skurcz mięśni brzucha w podporze przodem. Deska/ścianka/plank","ADVANCED";
insert into exercises (id,name,exercise_level) values 6,"Zginanie tułowia na maszynie siedząc. Spięcia brzucha na maszynie","BEGINNER";
insert into exercises (id,name,exercise_level) values 7,"T raise na ławeczce","ADVANCED";
insert into exercises (id,name,exercise_level) values 8,"Unoszenie ramion w przód ze sztangą w oparciu o ławkę dodatnią,"INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 9,"Arnoldki  wyciskanie hantli nad głowę z rotacją","ADVANCED";
insert into exercises (id,name,exercise_level) values 10,"Wiosło Pendlaya","BEGINNER";
insert into exercises (id,name,exercise_level) values 11,"Klasyczny martwy ciąg","ADVANCED";
insert into exercises (id,name,exercise_level) values 12,"Podciąganie na drążku trzymanym nachwytem","BEGINNER";
insert into exercises (id,name,exercise_level) values 13,"Prostopadłe przyciąganie drążka wyciągu górnego do bioder","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 14,"Unoszenie bioder z uniesionymi palcami stóp","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 15,"X walk","ADVANCED";
insert into exercises (id,name,exercise_level) values 16,"Wyciskanie na ławce skośnej w górę sztangą","ADVANCED";
insert into exercises (id,name,exercise_level) values 17,"Pompki w podporze tyłem na ławeczce","BEGINNER";
insert into exercises (id,name,exercise_level) values 18,"Rotacje z gumą","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 19,"Rowerek","BEGINNER";
insert into exercises (id,name,exercise_level) values 20,"Izometryczny skurcz mięśni brzucha w podporze przodem. Deska/ścianka/plank","ADVANCED";
insert into exercises (id,name,exercise_level) values 21,"Zginanie tułowia na maszynie siedząc. Spięcia brzucha na maszynie","BEGINNER";
insert into exercises (id,name,exercise_level) values 22,"T raise na ławeczce","ADVANCED";
insert into exercises (id,name,exercise_level) values 23,"Unoszenie ramion w przód ze sztangą w oparciu o ławkę dodatnią,"INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 24,"Arnoldki – wyciskanie hantli nad głowę z rotacją","ADVANCED";
insert into exercises (id,name,exercise_level) values 25,"Wiosło Pendlaya","BEGINNER";
insert into exercises (id,name,exercise_level) values 26,"Klasyczny martwy ciąg","ADVANCED";
insert into exercises (id,name,exercise_level) values 27,"Podciąganie na drążku trzymanym nachwytem","BEGINNER";
insert into exercises (id,name,exercise_level) values 28,"Prostopadłe przyciąganie drążka wyciągu górnego do bioder","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 29,"Unoszenie bioder z uniesionymi palcami stóp","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 30,"X walk","ADVANCED";
insert into exercises (id,name,exercise_level) values 31,"Wyciskanie na ławce skośnej w górę sztangą","ADVANCED";
insert into exercises (id,name,exercise_level) values 32,"Pompki w podporze tyłem na ławeczce","BEGINNER";
insert into exercises (id,name,exercise_level) values 33,"Rotacje z gumą","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 34,"Rowerek","BEGINNER";
insert into exercises (id,name,exercise_level) values 35,"Izometryczny skurcz mięśni brzucha w podporze przodem. Deska/ścianka/plank","ADVANCED";
insert into exercises (id,name,exercise_level) values 36,"Zginanie tułowia na maszynie siedząc. Spięcia brzucha na maszynie","BEGINNER";
insert into exercises (id,name,exercise_level) values 37,"T raise na ławeczce","ADVANCED";
insert into exercises (id,name,exercise_level) values 38,"Unoszenie ramion w przód ze sztangą w oparciu o ławkę dodatnią,"INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 39,"Arnoldki – wyciskanie hantli nad głowę z rotacją","ADVANCED";
insert into exercises (id,name,exercise_level) values 40,"Wiosło Pendlaya","BEGINNER";
insert into exercises (id,name,exercise_level) values 41,"Klasyczny martwy ciąg","ADVANCED";
insert into exercises (id,name,exercise_level) values 42,"Podciąganie na drążku trzymanym nachwytem","BEGINNER";
insert into exercises (id,name,exercise_level) values 43,"Prostopadłe przyciąganie drążka wyciągu górnego do bioder","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 44,"Unoszenie bioder z uniesionymi palcami stóp","INTERMEDIATE";
insert into exercises (id,name,exercise_level) values 45,"X walk","ADVANCED";