insert into exercise (id, exercise_level, name) values (1,'ADVANCED','Wyciskanie na ławce skośnej w górę sztangą');
insert into exercise (id, exercise_level, name) values (2,'BEGINNER','Pompki w podporze tyłem na ławeczce');
insert into exercise (id, exercise_level, name) values (3,'INTERMEDIATE','Rotacje z gumą');
insert into exercise (id, exercise_level, name) values (4,'BEGINNER','Rowerek');
insert into exercise (id, exercise_level, name) values (5,'ADVANCED','Izometryczny skurcz mięśni brzucha w podporze przodem. Deska/ścianka/plank');
insert into exercise (id, exercise_level, name) values (6,'BEGINNER','Zginanie tułowia na maszynie siedząc. Spięcia brzucha na maszynie');
insert into exercise (id, exercise_level, name) values (7,'ADVANCED','T raise na ławeczce');
insert into exercise (id, exercise_level, name) values (8,'INTERMEDIATE','Unoszenie ramion w przód ze sztangą w oparciu o ławkę dodatnią,');
insert into exercise (id, exercise_level, name) values (9,'ADVANCED','Arnoldki  wyciskanie hantli nad głowę z rotacją');
insert into exercise (id, exercise_level, name) values (10,'BEGINNER','Wiosło Pendlaya');
insert into exercise (id, exercise_level, name) values (11,'ADVANCED','Klasyczny martwy ciąg');
insert into exercise (id, exercise_level, name) values (12,'BEGINNER','Podciąganie na drążku trzymanym nachwytem');
insert into exercise (id, exercise_level, name) values (13,'INTERMEDIATE','Prostopadłe przyciąganie drążka wyciągu górnego do bioder');
insert into exercise (id, exercise_level, name) values (14,'INTERMEDIATE','Unoszenie bioder z uniesionymi palcami stóp');
insert into exercise (id, exercise_level, name) values (15,'ADVANCED','X walk');